apiVersion: v1
kind: ConfigMap
metadata:
  name: amr-prediction-config
data:
  LOG_LEVEL: "INFO"
  MODEL_PATH: artifact/amr_prediction_bundle.joblib
  MLFLOW_TRACKING_URI: http://mlflow.mlops:5000
  MODEL_NAME: churn
  MODEL_ALIAS: champion
